lock-service:
  image: lock-service
  environment:
    # The start of active environment variables. Set as needed.
    - MONGODB_IP=database
    # - MONGODB_PORT
    # - MONGODB_DATABASE=USE_HASKELL_DB
    - LOG_LEVEL=DEBUG
    # - https_proxy=http://www-proxy.scss.tcd.ie:8080
    # - http_proxy=http://www-proxy.scss.tcd.ie:8080
  command: /usr/local/bin/lock-service-exe
  ports:
    - "8002:8002"
  links:
    - database
database:
  image: mongo:3.0.2
  ports:
    - "27020:27017"
